repos:
-   repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 0.4.0 # the revision or tag to clone at
    hooks:
    -   id: sync_with_poetry
        args: ["--all"] # optional args
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    # -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.2.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
# -   repo: https://github.com/asottile/reorder_python_imports
#     rev: v3.9.0
#     hooks:
#     -   id: reorder-python-imports
#         exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
#         args: [--py38-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
# -   repo: https://github.com/pre-commit/mirrors-autopep8
#     rev: v2.0.2
#     hooks:
#     -   id: autopep8
-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        args: ["--max-line-length=88", "--ignore=E203,SIM106,ANN101,ANN102,E402,W503"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
        exclude: ^testing/resources/